FROM php:8-fpm-alpine
LABEL maintainer="Doug Clarke"

ARG user
ARG uid

RUN apk update \
  && apk add --no-cache autoconf openrc oniguruma-dev libpng-dev libxml2-dev zip unzip libmcrypt-dev openssl pcre-dev $PHPIZE_DEPS \
  && yes '' | pecl install redis \
  && docker-php-ext-install pdo_mysql exif pcntl bcmath gd \
  && docker-php-ext-enable redis

#COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

RUN adduser --disabled-password --uid $uid $user \
  && mkdir -p /home/$user/.composer \
  && chown -R $user:$user /home/$user

WORKDIR /var/www

USER $user
