---
version: "3"
services:
  ld-php:
    build:
      context: ../php-fpm
      dockerfile: Containerfile
    image: localdomain-alpine-php
    container_name: ld-php
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - '../../:/var/www/'
    networks:
      - localdomain-net
    depends_on:
      - ld-mysql
      - ld-nginx
      - ld-redis
  ld-mysql:
    image: mysql:8.0
    container_name: ld-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - '../mysql/initdb.d:/docker-entrypoint-initdb.d'
      - 'mysqldata:/var/lib/mysql'
    networks:
      - localdomain-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
  ld-nginx:
    image: nginxinc/nginx-unprivileged:1.18-alpine
    container_name: ld-nginx
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - '../../:/var/www'
      - '../nginx/conf.d:/etc/nginx/conf.d'
    networks:
      - localdomain-net
  ld-redis:
    image: redis:6-alpine
    container_name: ld-redis
    restart: unless-stopped
    volumes:
      - 'redisdata:/data'
    networks:
      - localdomain-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
networks:
  localdomain-net:
    driver: bridge
volumes:
  mysqldata:
    driver: local
  redisdata:
    driver: local
